config/routes.rb
Aatedb::Application.routes.draw do
  resources :tags

  resources :categories

  resources :assets

  resources :authors

  resources :shows

  root :to => 'assets#index'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
    attr_accessible :checksum, :description, :duration, :file, :filesize, :visability, :height, :path, :release, :show_id, :state, :title, :dlcount, :aspect, :media, :width, :author_ids, :category_id, :agelimit, :agelimitreason
    belongs_to :show
    belongs_to :category
    has_and_belongs_to_many :authors
    has_and_belongs_to_many :tags

    mount_uploader :file, AssetUploader

    before_save :store_metadata #fill in record metadata
    after_save  :enqueue #render webfiles

    validates_presence_of :agelimitreason, :if => :agelimit_set?
    validates_presence_of :title, :description, :release, :show, :category, :authors
    validates_associated :tags

    def self.agelimits
        {"N/A" => 0, "K7" => 7,"K11" => 11,"K13" => 13,"K15" => 15,"K18" => 18}
    end

    def self.visability_modes
        {"All" => 0, "No Internet" => 1}
    end

    VIDEO = 1
    IMAGE = 2
    AUDIO = 3

    def self.is_video?
        self.media == VIDEO
    end

    def self.is_image?
        self.media == IMAGE
    end

    def self.is_audio?
        self.media == AUDIO
    end

    def agelimit_set?
        agelimit != 0
    end

    state_machine :initial => :pending do

        event :screenshot do
            transition :pending => :screenshotmade
        end

        event :convert do
            transition :screenshotmade => :converting
        end

        event :converted do
            transition :converting => :converted
        end

        event :convertfail do
            transition :converting => :error
        end

    end

    def tag!(tags)
        newtags = tags.split(", ").map do |tag|
            Tag.find_or_create_by_name(tag)
        end

        remove = self.tags.select {|r| newtags.exclude? r}
        add    = newtags.select {|a| self.tags.exclude? a}
        add.uniq!
        remove.each do |r|
            self.tags.delete(r)
        end

        self.tags << add
    end

    #  # Returns filename camelized. Replace non-alphanumeric, underscore and periods with "camelization"
    #def sanitize_filename(value)
    #  # get only the filename, not the whole path
    #  just_filename = value.gsub(/^.*(\\|\/)/, '')
    #  # NOTE: File.basename doesn't work right with Windows paths on Unix
    #  # INCORRECT: just_filename = File.basename(value.gsub('\\\\', '/')) 

    #  # Finally, replace all non alphanumeric, underscore or periods with underscore in the filename and camilizes it
    #  just_filename.gsub(/[^\w\.\-]/,'_').camelize
    #end

    private
    def store_metadata
        if self.file.present? && self.changed.include?("file") 
            file_path = "#{Rails.root}/public/#{file}"
            file = Mediainfo.new file_path
            common_meta(file, file_path)
            if file.image?
                image_meta(file)
                self.media = IMAGE
            elsif file.video?
                video_meta(file)
                self.media = VIDEO
            elsif file.audio?
                audio_meta(file)
                self.media = AUDIO
            end
        end
    end

    def common_meta(file, file_path)
        self.filesize = file.size
        self.checksum = ::Digest::MD5.file(file_path).hexdigest
        self.container = file.format
        self.path = File.dirname(file_path)
    end

    def video_meta(file)
        self.duration = file.video.duration
        self.width = file.video.width
        self.height = file.video.height
        self.bitrate = file.overall_bit_rate
        self.framerate = file.video.frame_rate
        self.aspect = file.video.display_aspect_ratio
        self.vcodec = "#{file.video.format_info} / #{file.video.format_profile} / #{file.video.codec_id}"
        self.interlaced = 1 if file.video.interlaced?
        if file.audio.count == 0
            self.samplerate  = 0
            self.acodec = "NOAUDIO"
            self.channels = "NOAUDIO"
        else
            self.samplerate = file.audio.parsed_response[:audio]['sampling_rate']
            self.acodec = file.audio.parsed_response[:audio]['format_profile']
            self.channels = file.audio.parsed_response[:audio]['channel_s']
        end
    end

    def image_meta(file)
        self.width = file.image.width
        self.height = file.image.height
        self.bitrate = file.image[0].parsed_response[:image]['bit_depth']
        self.vcodec = file.image[0].parsed_response[:image]['format_compression']
        self.aspect = self.width/self.height
    end

    def audio_meta(file)
        self.duration = file.duration
        self.bitrate = file.overall_bit_rate
        self.samplerate = file.audio.parsed_response[:audio]['sampling_rate']
        self.acodec = file.audio.parsed_response[:audio]['format_profile']
        self.channels = file.audio.parsed_response[:audio]['channel_s']
    end


end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
    # GET /assets
    # GET /assets.json
    def index
        @assets = Asset.all

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @assets }
        end
    end

    # GET /assets/1
    # GET /assets/1.json
    def show
        @asset = Asset.find(params[:id])

        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @asset }
        end
    end

    # GET /assets/new
    # GET /assets/new.json
    def new
        @asset = Asset.new
        @shows = Show.all
        @authors = Author.all
        @categories = Category.all
        @agelimits = Asset.agelimits
        @visability_modes = Asset.visability_modes

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @asset }
        end
    end

    # GET /assets/1/edit
    def edit
        @asset = Asset.find(params[:id])
        @shows = Show.all
        @authors = Author.all
        @categories = Category.all
        @agelimits = Asset.agelimits
        @visability_modes = Asset.visability_modes

        params[:tags] = @asset.tags.collect{|t| t.name}.join(", ")
    end

    # POST /assets
    # POST /assets.json
    def create
        @asset = Asset.new(params[:asset])
        @shows = Show.all
        @authors = Author.all
        @categories = Category.all
        @agelimits = Asset.agelimits
        @visability_modes = Asset.visability_modes

        respond_to do |format|
            if @asset.save
                @asset.tag!(params[:tags])
                format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
                format.json { render json: @asset, status: :created, location: @asset }
            else
                format.html { render action: "new" }
                format.json { render json: @asset.errors, status: :unprocessable_entity }
            end
        end
    end

    # PUT /assets/1
    # PUT /assets/1.json
    def update
        @asset = Asset.find(params[:id])
        @shows = Show.all
        @authors = Author.all
        @categories = Category.all
        @agelimits = Asset.agelimits
        @visability_modes = Asset.visability_modes

        params[:tags] = @asset.tags.collect{|t| t.name}.join(", ")

        respond_to do |format|
            if @asset.update_attributes(params[:asset])
                @asset.tag!(params[:tags])
                format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @asset.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /assets/1
    # DELETE /assets/1.json
    def destroy
        @asset = Asset.find(params[:id])
        @asset.destroy

        respond_to do |format|
            format.html { redirect_to assets_url }
            format.json { head :no_content }
        end
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset, :html => {:multipart => true} ) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :visability %><br />
    <%= f.select :visability, @visability_modes %>
  </div>
  <div class="field">
    <%= f.label :agelimit %><br />
    <%= f.select :agelimit, @agelimits %>
  </div>
  <div class="field">
    <%= f.label :agelimitreason %><br />
    <%= f.text_field :agelimitreason %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release, :value => Date.today %>
  </div>
  <div class="field">
    <%= f.label :show_id %><br />
    <%= f.select :show_id, @shows.collect { |s| [ s.name, s.id ]}, { :include_blank => true } %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories.collect { |c| [ c.name, c.id ]}, { :include_blank => true } %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <%= text_field_tag :tags, params[:tags] %>
  </div>
  <% unless @asset.file.present? %>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :file %>
  </div>
  <% end %>
  <div class="field">
    <% f.label :authors %><br />
    <% @authors.each do |author| %>
    <%= check_box_tag 'asset[author_ids][]', author.id, @asset.authors.include?(author) %>
    <%= author.name %><br />
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th>Title</th>
    <th>Description</th>
    <th>File</th>
    <th>Path</th>
    <th>Show</th>
    <th>Cateogry</th>
    <th>Tags</th>
    <th>Authors</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assets.each do |asset| %>
  <tr>
    <td>
        <%= image_tag("transfer-green.png", :width => 16) if asset.visability == 0 %>
        <%= image_tag("transfer-red.png",   :width => 16) if asset.visability == 1 %>
        <%= image_tag("transfer-blue.png",  :width => 16) if asset.visability == 2 %>
    </td>
    <td>
    <%= image_tag("image-file-icon.png", :width => 16) if asset.media == Asset::IMAGE %>
    <%= image_tag("video-file-icon.png", :width => 16) if asset.media == Asset::VIDEO %>
    <%= image_tag("audio-file-icon.png", :width => 16) if asset.media == Asset::AUDIO %>
    </td>
        <td><b><%= asset.title %><b></td>
    <td><%= asset.description %></td>
    <td><%= asset.file %></td>
    <td><%= asset.path %></td>
    <td><%= asset.show.name %></td>
    <td><%= asset.category.name %></td>
    <td><%= render asset.tags %></td>
    <td><%= asset.authors.collect{|a| a.name}.to_sentence unless nil? %></td>
    <td><%= link_to 'Show', asset %></td>
    <td><%= link_to image_tag('wheel-icon.png', :width => 16), edit_asset_path(asset) %></td>
    <td><%= link_to image_tag('remove-from-database-icon.png', :width => 16), asset, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to (image_tag('add-to-database-icon.png', :width => 16) << 'New Asset'), new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Visability:</b>
  <%= @asset.visability %>
</p>

<p>
  <b>Title:</b>
  <%= @asset.title %>
</p>

<p>
  <b>Description:</b>
  <%= @asset.description %>
</p>

<p>
  <b>Release:</b>
  <%= @asset.release %>
</p>

<p>
  <b>Media:</b>
  <%= @asset.media %>
</p>

<p>
  <b>File:</b>
  <%= @asset.file%>
</p>

<p>
  <b>Agelimit:</b>
  <%= @asset.agelimit %>
</p>

<p>
  <b>Agelimitreason:</b>
  <%= @asset.agelimitreason %>
</p>

<p>
  <b>Checksum:</b>
  <%= @asset.checksum %>
</p>

<p>
  <b>Path:</b>
  <%= @asset.path %>
</p>

<p>
  <b>Filesize:</b>
  <%= @asset.filesize %>
</p>

<p>
  <b>Width:</b>
  <%= @asset.width %>
</p>

<p>
  <b>Height:</b>
  <%= @asset.height %>
</p>

<p>
  <b>Aspect:</b>
  <%= @asset.aspect %>
</p>

<p>
  <b>Bitrate:</b>
  <%= @asset.bitrate %>
</p>

<p>
  <b>Framerate:</b>
  <%= @asset.framerate %>
</p>

<p>
  <b>Samplerate:</b>
  <%= @asset.samplerate %>
</p>

<p>
  <b>Vcodec:</b>
  <%= @asset.vcodec %>
</p>

<p>
  <b>Acodec:</b>
  <%= @asset.acodec %>
</p>

<p>
  <b>Channels:</b>
  <%= @asset.channels %>
</p>

<p>
  <b>Container:</b>
  <%= @asset.container %>
</p>

<p>
  <b>Duration:</b>
  <%= @asset.duration %>
</p>

<p>
  <b>State:</b>
  <%= @asset.state %>
</p>

<p>
  <b>Show:</b>
  <%= @asset.show.name %>
</p>

<p>
  <b>Category:</b>
  <%= @asset.category.name %>
</p>

<p>
  <b>Tags:</b>
  <%= render @asset.tags %>
</p>

<p>
  <b>Authors:</b>
  <%= @asset.authors.collect{|a| a.name}.to_sentence %>
</p>

<p>
  <b>Dlcount:</b>
  <%= @asset.dlcount %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>